/**
 * RestStudio - Offline-First REST API Client & Workspace
 * Created by Suhail Akhtar (https://suhail.top)
 */

import { Project, RestFile, RestRequest } from '../types';
import { generateCodeSnippet } from './codeSnippetGenerator';

export interface DocExportOptions {
  title?: string;
  subtitle?: string;
  baseUrl?: string;
  version?: string;
  author?: string;
  includeCodeSnippets?: boolean;
}

/**
 * Generates a clean, GitHub-flavored Markdown document for a Project / Collection
 */
export function generateMarkdownDocs(project: Project, options: DocExportOptions = {}): string {
  const title = options.title || project.name || 'API Documentation';
  const subtitle = options.subtitle || project.description || 'RestStudio Generated REST API Specification';
  const baseUrl = options.baseUrl || 'https://api.example.com';
  const version = options.version || 'v1.0.0';
  const author = options.author || 'Suhail Akhtar (suhail.top)';

  let md = `# ${title}\n\n`;
  md += `> **Version:** ${version}  \n`;
  md += `> **Base URL:** \`${baseUrl}\`  \n`;
  md += `> **Generated by:** [RestStudio](https://suhail.top) by ${author}\n\n`;

  if (subtitle) {
    md += `${subtitle}\n\n`;
  }

  md += `---\n\n`;
  md += `## Table of Contents\n\n`;

  const files = project.files || [];
  files.forEach((file, fileIdx) => {
    md += `${fileIdx + 1}. [${file.name}](#${slugify(file.name)})\n`;
    (file.requests || []).forEach((req) => {
      md += `   - [${req.method} ${req.name}](#${slugify(`${file.name}-${req.name}`)})\n`;
    });
  });

  md += `\n---\n\n`;

  files.forEach((file) => {
    md += `## ${file.name}\n\n`;
    if (file.description) {
      md += `${file.description}\n\n`;
    }

    (file.requests || []).forEach((req) => {
      md += `### ${req.name} <a id="${slugify(`${file.name}-${req.name}`)}"></a>\n\n`;
      md += `\`${req.method}\` \`${req.url || '/'}\`  \n\n`;

      if (req.description) {
        md += `${req.description}\n\n`;
      }

      // Headers
      const activeHeaders = (req.headers || []).filter((h) => h.enabled && h.key);
      if (activeHeaders.length > 0) {
        md += `#### Request Headers\n\n`;
        md += `| Header | Value | Description |\n`;
        md += `| :--- | :--- | :--- |\n`;
        activeHeaders.forEach((h) => {
          md += `| \`${escapeMd(h.key)}\` | \`${escapeMd(h.value)}\` | ${escapeMd(h.description || '-')} |\n`;
        });
        md += `\n`;
      }

      // Query Params
      const activeParams = (req.queryParams || []).filter((p) => p.enabled && p.key);
      if (activeParams.length > 0) {
        md += `#### Query Parameters\n\n`;
        md += `| Parameter | Sample Value | Description |\n`;
        md += `| :--- | :--- | :--- |\n`;
        activeParams.forEach((p) => {
          md += `| \`${escapeMd(p.key)}\` | \`${escapeMd(p.value)}\` | ${escapeMd(p.description || '-')} |\n`;
        });
        md += `\n`;
      }

      // Body Payload
      if (req.body && req.body.mode !== 'none') {
        md += `#### Request Body (${req.body.mode})\n\n`;
        if (req.body.mode === 'json' && req.body.rawText) {
          md += `\`\`\`json\n${req.body.rawText}\n\`\`\`\n\n`;
        } else if (req.body.mode === 'form-data' && (req.body.formDataItems || []).length > 0) {
          md += `| Key | Type | Value |\n`;
          md += `| :--- | :--- | :--- |\n`;
          (req.body.formDataItems || []).filter((f) => f.enabled).forEach((f) => {
            md += `| \`${escapeMd(f.key)}\` | \`${f.type}\` | \`${escapeMd(f.value || '')}\` |\n`;
          });
          md += `\n`;
        }
      }

      // Sample Code Snippet
      const cUrlCode = generateCodeSnippet('curl', req);
      md += `#### Example Request (cURL)\n\n`;
      md += `\`\`\`bash\n${cUrlCode}\n\`\`\`\n\n`;

      md += `---\n\n`;
    });
  });

  md += `*Documentation generated automatically by [RestStudio](https://suhail.top)*\n`;
  return md;
}

/**
 * Generates a beautiful, responsive, self-contained HTML page
 */
export function generateHtmlDocs(project: Project, options: DocExportOptions = {}): string {
  const title = options.title || project.name || 'API Documentation';
  const subtitle = options.subtitle || project.description || 'RestStudio Generated REST API Specification';
  const baseUrl = options.baseUrl || 'https://api.example.com';
  const version = options.version || 'v1.0.0';
  const author = options.author || 'Suhail Akhtar (suhail.top)';

  const markdownContent = generateMarkdownDocs(project, options);

  return `<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="${author}">
  <title>${escapeHtml(title)} - API Documentation</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; }
    pre { background: #0f172a; color: #f8fafc; padding: 1rem; border-radius: 0.75rem; overflow-x: auto; }
    code { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; }
  </style>
</head>
<body class="bg-slate-950 text-slate-100 min-h-screen flex flex-col">
  <header class="border-b border-slate-800 bg-slate-900/90 backdrop-blur sticky top-0 z-30 px-6 py-4 flex items-center justify-between">
    <div>
      <h1 class="text-xl font-bold tracking-tight text-white">${escapeHtml(title)}</h1>
      <p class="text-xs text-slate-400 mt-0.5">${escapeHtml(subtitle)} &bull; Base URL: <code class="text-emerald-400">${escapeHtml(baseUrl)}</code></p>
    </div>
    <div class="flex items-center space-x-3 text-xs font-mono">
      <span class="px-2.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-semibold">${escapeHtml(version)}</span>
      <span class="text-slate-500">Generated by RestStudio</span>
    </div>
  </header>

  <div class="flex-1 flex max-w-7xl w-full mx-auto px-6 py-8 gap-8">
    <!-- Sidebar Navigation -->
    <aside class="w-64 shrink-0 hidden md:block border-r border-slate-800 pr-6 space-y-6 sticky top-24 h-[calc(100vh-8rem)] overflow-y-auto">
      <div>
        <h3 class="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">API Collections</h3>
        <nav class="space-y-4">
          ${(project.files || []).map((file) => `
            <div>
              <div class="text-xs font-bold text-slate-200 mb-1.5 flex items-center space-x-1.5">
                <span>📁</span>
                <span>${escapeHtml(file.name)}</span>
              </div>
              <ul class="space-y-1 pl-3 text-xs">
                ${(file.requests || []).map((req) => `
                  <li>
                    <a href="#req-${req.id}" class="flex items-center space-x-2 text-slate-400 hover:text-emerald-400 transition-colors py-1">
                      <span class="px-1.5 py-0.5 rounded text-[9px] font-mono font-bold ${getMethodBadgeClass(req.method)}">${req.method}</span>
                      <span class="truncate">${escapeHtml(req.name)}</span>
                    </a>
                  </li>
                `).join('')}
              </ul>
            </div>
          `).join('')}
        </nav>
      </div>
    </aside>

    <!-- Main Content -->
    <main class="flex-1 space-y-10 min-w-0">
      ${(project.files || []).map((file) => `
        <section class="space-y-6">
          <div class="border-b border-slate-800 pb-3">
            <h2 class="text-2xl font-bold text-white flex items-center space-x-2">
              <span>📁</span>
              <span>${escapeHtml(file.name)}</span>
            </h2>
            ${file.description ? `<p class="text-sm text-slate-400 mt-1">${escapeHtml(file.description)}</p>` : ''}
          </div>

          <div class="space-y-8">
            ${(file.requests || []).map((req) => `
              <article id="req-${req.id}" class="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 space-y-4 shadow-xl">
                <div class="flex items-center justify-between gap-3">
                  <h3 class="text-lg font-bold text-slate-100">${escapeHtml(req.name)}</h3>
                  <span class="px-2.5 py-1 rounded-lg text-xs font-mono font-bold ${getMethodBadgeClass(req.method)}">${req.method}</span>
                </div>

                <div class="flex items-center space-x-2 bg-slate-950 px-3 py-2 rounded-xl border border-slate-800/80 font-mono text-xs text-slate-300 overflow-x-auto">
                  <span class="text-slate-500 font-bold">${req.method}</span>
                  <span class="text-emerald-400">${escapeHtml(req.url || '/')}</span>
                </div>

                ${req.description ? `<p class="text-xs text-slate-400 leading-relaxed">${escapeHtml(req.description)}</p>` : ''}

                ${(req.headers || []).filter(h => h.enabled && h.key).length > 0 ? `
                  <div class="space-y-2">
                    <h4 class="text-xs font-bold uppercase tracking-wider text-slate-400">Headers</h4>
                    <div class="overflow-x-auto border border-slate-800 rounded-xl">
                      <table class="w-full text-xs text-left text-slate-300">
                        <thead class="bg-slate-950 text-slate-400 text-[11px] uppercase border-b border-slate-800">
                          <tr>
                            <th class="px-4 py-2">Header</th>
                            <th class="px-4 py-2">Value</th>
                            <th class="px-4 py-2">Description</th>
                          </tr>
                        </thead>
                        <tbody class="divide-y divide-slate-800/60">
                          ${(req.headers || []).filter(h => h.enabled && h.key).map(h => `
                            <tr>
                              <td class="px-4 py-2 font-mono text-emerald-400">${escapeHtml(h.key)}</td>
                              <td class="px-4 py-2 font-mono text-slate-300">${escapeHtml(h.value)}</td>
                              <td class="px-4 py-2 text-slate-400">${escapeHtml(h.description || '-')}</td>
                            </tr>
                          `).join('')}
                        </tbody>
                      </table>
                    </div>
                  </div>
                ` : ''}

                ${req.body && req.body.mode === 'json' && req.body.rawText ? `
                  <div class="space-y-2">
                    <h4 class="text-xs font-bold uppercase tracking-wider text-slate-400">Request Body (JSON)</h4>
                    <pre><code>${escapeHtml(req.body.rawText)}</code></pre>
                  </div>
                ` : ''}

                <div class="space-y-2">
                  <h4 class="text-xs font-bold uppercase tracking-wider text-slate-400">cURL Example</h4>
                  <pre><code class="text-amber-300">${escapeHtml(generateCodeSnippet('curl', req))}</code></pre>
                </div>
              </article>
            `).join('')}
          </div>
        </section>
      `).join('')}
    </main>
  </div>

  <footer class="border-t border-slate-800 py-6 text-center text-xs text-slate-500 font-mono">
    Created by <a href="https://suhail.top" target="_blank" rel="noopener noreferrer" class="text-emerald-400 hover:underline">Suhail Akhtar</a> &bull; Generated with RestStudio
  </footer>
</body>
</html>`;
}

function getMethodBadgeClass(method: string): string {
  switch (method.toUpperCase()) {
    case 'GET': return 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30';
    case 'POST': return 'bg-sky-500/20 text-sky-400 border border-sky-500/30';
    case 'PUT': return 'bg-amber-500/20 text-amber-400 border border-amber-500/30';
    case 'DELETE': return 'bg-rose-500/20 text-rose-400 border border-rose-500/30';
    case 'PATCH': return 'bg-purple-500/20 text-purple-400 border border-purple-500/30';
    default: return 'bg-slate-500/20 text-slate-400 border border-slate-500/30';
  }
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^\w\s-]/g, '').replace(/[\s_-]+/g, '-').replace(/^-+|-+$/g, '');
}

function escapeHtml(str: string = ''): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function escapeMd(str: string = ''): string {
  return str.replace(/\|/g, '\\|');
}
